name: SimpleNoBeamBeacon
version: '${version}'
main: com.captainratax.simplenobeambeacon.SimpleNoBeamBeaconPlugin
description: Keeps beacon effects active when tinted glass hides the beam.
author: CaptainRatax
license: MIT
api-version: '1.17'
